[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["snake"]
py-modules = ["myAI", "myEnv"]

[project]
name = "snake-ai"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "pyyaml>=6.0.3",
    "raylib>=5.5.0.3",
    "tqdm>=4.67.1",

    # Uncomment these two to train a reinforcement learning agent.
    # See the "Reinforcement Learning" section of the README.
    # "gymnasium>=1.0",
    # "stable-baselines3>=2.4",
]

[project.scripts]
snake = "snake.snake:main"
